[package]
name = "yada-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = { version = "4.4.0", default-features = false, features = ["tokio"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "signal"] }
anyhow = "1.0.95"
yada-core = { path = "../yada-core" }
