[project]
name = "research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "requests>=2.32.5",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
]
